import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import Image from "next/image";

import NextImage from '../public/image.png'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const myImageLoader = ({ src, width, quality }) => {
    return `https://stimg2.cardekho.com/images/roadTestimages/userimages/671/1597674082017/GeneralRoadTest.jpg?tr=w-${width}?tr=w-${width}`
  }
  return (
    <>
      <Head>
        <title>Raj Thombare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Raj Thombare</h1>
        <p>I am a Frontend Engineer!</p>
        <p>I love building things.</p>
        <br />
        <Link href="/users">Static Page</Link>
        <br />
        <Link href="/server/users">SSR</Link>
        <br />
        <Link href="/static/users">SSG</Link>
        <br />
        <br />
        <Link href="/quotes">Quotes Page</Link>
        <br />
        <br />
        {/* <Image src={NextImage} alt="Next Image" width={500} height={300} /> */}
        <Image loader={myImageLoader} src={"https://stimg2.cardekho.com/images/roadTestimages/userimages/671/1597674082017/GeneralRoadTest.jpg?tr=w-360?tr=w-320"} alt="Next Image" width={300} height={200} />
      </main>
    </>
  );
}

// file based routing
// nested routes
// dynamic routes
// client side data fetching

/**
 * * important info
 * ? public api
 * ! deprecated method
 * TODO: better comments
 */
