import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Raj Thombare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Raj Thombare</h1>
        <p>I am a Frontend Engineer!</p>
        <p>I love building things.</p>
        <br />
        <Link href="/news">News Page</Link>
        <br />
        <br />
        <Link href="/quotes">Quotes Page</Link>
      </main>
    </>
  );
}

// file based routing
// nested routes
// dynamic routes
// client side data fetching

/**
 * * important info
 * ? public api
 * ! deprecated method
 * TODO: better comments
 */
